import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Unnamed Journey</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(0,0%,80%)]">Unnamed</span>{' '}
            <span className="text-[hsl(240,100%,70%)]">Journey</span>
          </h1>
          <h4 className="text-2xl font-bold text-white">
            One day it will have a name, and it will look gorgeous. For now, official policy is to
            settle for good enough!
          </h4>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 align-middle justify-center text-center"
              href="/entries/create"
            >
              <h3 className="text-2xl font-bold p-2">Create a new entry</h3>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 align-middle justify-center text-center"
              href="/entries/view"
            >
              <h3 className="text-2xl font-bold p-2">View entries</h3>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
